version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret123'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'secret123'
      MYSQL_DATABASE: 'workshop'
    volumes:
      - "./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"

  php:
    build:
      context: .
      dockerfile: build/PHP.Dockerfile
    volumes:
      - "./src/php/app:/app/public"
    env_file:
      - "./src/php/env/php.env"
networks:
  workshop: